Automatic detection of boolean fields
PetrDlouhy/django-related-admin pull request #7
Opened 2017-04-18 21:11 UTC by theY4Kman

Adds support for automatically detecting boolean fields, so you can get 
![selection_014](https://cloud.githubusercontent.com/assets/33840/25153179/aa25e778-2459-11e7-9d87-2adcdade6808.png)

Instead of
![selection_015](https://cloud.githubusercontent.com/assets/33840/25153193/b6f17c88-2459-11e7-9511-980b16e129d1.png)

By only listing the field in `list_display` (like vanilla Django)
```python
class AlbumAdmin(RelatedFieldAdmin):
    list_display = ('artist__active',)
```

And without requiring an explicit `boolean=True`:
```python
class AlbumAdmin(RelatedFieldAdmin):
    list_display = ('artist__active',)

    # Not needed
    artist__active = getter_for_related_field('artist__active', boolean=True)
```

2017-04-18 21:21 UTC, PetrDlouhy requested changes
@theY4Kman Very nice!

Can you please mention that in `README.rst`, correct the tests and code style, please?

2017-04-18 21:21 UTC, PetrDlouhy commented on related_admin/__init__.py
> -
Can you please leave double spacing before classes?

2017-04-18 21:31 UTC, theY4Kman commented
Done, done, and done. Will that note do, or would you like something more substantial?

Also, I'll squash the commits before you merge.

2017-04-18 21:41 UTC, theY4Kman commented
Er, did I break something on that flake8 test? https://travis-ci.org/PetrDlouhy/django-related-admin/jobs/223329049

2017-04-18 21:52 UTC, PetrDlouhy commented
@theY4Kman `flake8-class` disappeared from PyPI. Please, remove it from deps and you will be OK.

2017-04-20 16:27 UTC, theY4Kman commented
Okie dokes, that should cover everything. If you're satisfied, I'll go ahead and squash.

2017-04-20 16:45 UTC, PetrDlouhy commented
Nice, I like it. Please squash and add one more commit - bump the version to `0.5.0`.


I will release version `1.0.0` after some time this version will be alive without bugs.

2017-04-20 16:54 UTC, theY4Kman commented
Done and done. I left the flake8 fix as a separate commit, since it seemed unrelated.

2017-04-22 10:46 UTC, merged

2017-04-24 16:42 UTC, PetrDlouhy commented
@theY4Kman Merged and now also released on PyPI. Thanks for your contribution.

2017-04-25 16:47 UTC, theY4Kman commented
Kick-ass :D Thanks for the project. I was a bit taken aback by the lack of relationship support in list_display and the Django project's outright *refusal* to address it. This project definitely stopped me from jamming my foot in someone's rear ;)